// Presentation layer: keep economic formulas and save schema unchanged.
function kmFitDomain238(){const view=document.querySelector('.km-map-viewport'),map=document.getElementById('km-domain-map');if(!view||!map)return;const zoom=Number(map.dataset.zoom)||1;map.style.width=view.clientWidth*zoom+'px';map.style.height=view.clientWidth*1.5*zoom+'px';}
const KM_SCENES239={wood:'0% 0%',ore:'100% 0%',herb:'0% 50%',magic:'100% 50%'};
const kmOpenBuild239=openV15Build;
openV15Build=function(kind,key){kmOpenBuild239(kind,key);const art=document.querySelector('.v15-build-art');if(kind==='gather')art.style.backgroundPosition=KM_SCENES239[key];document.querySelector('.v15-build-body').scrollTop=0;};
function renderGathering(){document.getElementById('gathering-container').innerHTML=Object.entries(GATHERING_NODES).map(([key,n])=>{const busy=!!gameState.upgradesInProgress['gather:'+key];return `<button id="gather-${key}" class="km-gather239 ${busy?'upgrading':''}" onclick="openV15Build('gather','${key}')" style="--scene-position:${KM_SCENES239[key]}"><span class="km-gather-scene239"></span><span class="km-gather-info239">${kmResourceArt238(n.resKey)}<strong>${n.name}<small>Lv.${n.level} · 초당 +${formatNumber(n.level*n.prodRate*KM_ECONOMY_V217.production.gatheringMultiplier)}</small></strong><span class="km-gather-action239">${busy?'확장 중':'관리 ›'}</span></span><span class="progress-bar-container" id="progress-container-${key}" style="display:${busy?'block':'none'}"><span class="progress-bar-fill" id="progress-fill-${key}"></span><span class="progress-bar-text" id="progress-text-${key}"></span></span></button>`;}).join('');}
let kmHeroFilter239='all',kmHeroSelected239=null;
function kmPortrait239(i){return `background-position:${(i%7)*100/6}% ${Math.floor(i/7)*50}%`;}
function kmFilterHeroes239(type){kmHeroFilter239=type;renderHeroes();}
function renderHeroes(){const types=[['all','전체'],['infantry','보병'],['cavalry','기병'],['archer','궁병']];let html='<div class="km-hero-filters239">'+types.map(([t,n])=>`<button onclick="kmFilterHeroes239('${t}')" aria-pressed="${kmHeroFilter239===t}">${n}</button>`).join('')+'</div><div class="km-hero-grid239">';HEROES.forEach((h,i)=>{if(kmHeroFilter239!=='all'&&kmHeroFilter239!==h.type)return;const peers=HEROES.map((h,idx)=>({h,idx})).filter(x=>x.h.type===h.type),tier=peers.findIndex(x=>x.idx===i),unlocked=tier<=getHighestUnlockedHeroTierV196(peers);html+=`<button class="km-hero-card239 ${unlocked?'':'km-locked239'}" onclick="kmOpenHero239(${i})" aria-label="${h.name} ${unlocked?'Lv.'+h.level:'잠김'}"><span class="km-portrait239" style="${kmPortrait239(i)}"></span><span class="km-hero-caption239"><b>${unlocked?'Lv.'+h.level:'잠김'}</b><small>${h.name}</small></span>${gameState.upgradesInProgress['hero:'+i]?'<span class="km-training239">훈련 중</span>':''}</button>`;});document.getElementById('heroes-container').innerHTML=html+'</div>';if(kmHeroSelected239!==null)kmRefreshHero239();}
function kmOpenHero239(i){kmHeroSelected239=i;kmRefreshHero239();document.getElementById('km-hero-detail239').hidden=false;document.getElementById('km-hero-close239').focus();}
function kmCloseHero239(){document.getElementById('km-hero-detail239').hidden=true;kmHeroSelected239=null;}
function kmRefreshHero239(){const i=kmHeroSelected239;if(i===null)return;const h=HEROES[i],peers=HEROES.map((h,idx)=>({h,idx})).filter(x=>x.h.type===h.type),tier=peers.findIndex(x=>x.idx===i),unlocked=tier<=getHighestUnlockedHeroTierV196(peers),s=getHeroStats(h),costs=getHeroUpgradeCostsV206(h,tier),busy=!!gameState.upgradesInProgress['hero:'+i];document.getElementById('km-hero-detail-content239').innerHTML=`<div class="km-hero-detail-portrait239 km-portrait239" style="${kmPortrait239(i)}"></div><h2>${h.name} <small>Lv.${h.level}</small></h2><p>공격력 ${formatNumber(s.atk)} · 체력 ${formatNumber(s.hp)}</p>${unlocked?`<div class="km-hero-cost239">${heroCostsHtmlV206(costs)}</div><p>훈련 시간 ${getHeroUpgradeTimeV194(h)}초</p><div id="progress-container-hero:${i}" class="progress-bar-container" style="display:${busy?'block':'none'}"><div id="progress-fill-hero:${i}" class="progress-bar-fill"></div><div id="progress-text-hero:${i}" class="progress-bar-text"></div></div><div class="km-hero-actions239"><button onclick="kmCloseHero239();openEquipmentModal(${i})">장비 관리</button><button id="btn-hero-${i}" onclick="startHeroUpgrade(${i},this);kmRefreshHero239()" ${busy?'disabled':''}>${busy?'훈련 중':'훈련 시작'}</button></div>`:`<p>${getHeroUnlockTextV196(peers,tier)} 달성 시 해금됩니다.</p>`}`;}
function renderShop(){document.getElementById('shop-container').innerHTML=SHOP_ITEMS.map(item=>`<div class="shop-item">${kmResourceArt238(item.rewardType|| (item.costType==='cash'?'crown':'gem'))}<strong>${item.name}</strong><p>${item.desc}</p><button class="btn-3d btn-orange" onclick="buyShopItem('${item.id}');playSfx('click')">${item.btnText}</button></div>`).join('');}
const kmBattleUnits239=renderBattleUnitsV12;
renderBattleUnitsV12=function(){kmBattleUnits239();BATTLE_V12.heroes.forEach((u,i)=>{const el=document.querySelector('#fighter-v12-'+i+' .unit');if(el){const col=u.type==='archer'?3:u.type==='cavalry'?2:HEROES[u.idx]?.level>=10?1:0;el.style.setProperty('--sprite-pos',`${col*100/3}% 0%`);}});const el=document.getElementById('enemy-unit-v12');if(el)el.style.setProperty('--sprite-pos',`${BATTLE_V12.enemy.boss?100:((Math.max(1,gameState.towerFloor||1)-1)%3)*100/3}% 100%`);};
function kmInit239(){const card=document.querySelector('.v15-build-card'),body=card.querySelector('.v15-build-body'),art=card.querySelector('.v15-build-art');body.prepend(art);const footer=document.createElement('div');footer.className='km-detail-actions239';footer.append(document.getElementById('km-detail-status'),document.getElementById('v15-build-go'));card.append(footer);document.querySelector('#screen-heroes>div:not(#heroes-container)')?.remove();document.addEventListener('keydown',e=>{if(e.key==='Escape')kmCloseHero239();});kmFitDomain238();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',kmInit239);else kmInit239();
heroCostsHtmlV206=function(costs){return Object.entries(costs).map(([key,n])=>`<span>${kmResourceArt238(key)}${formatNumber(n)}</span>`).join('');};
updateSquadSummary=function(){const box=document.getElementById('battle-squad-preview-container'),badge=document.getElementById('squad-count-num-badge');if(badge)badge.textContent=gameState.selectedSquad.length;if(box)box.innerHTML=gameState.selectedSquad.length?gameState.selectedSquad.map(i=>`<div class="km-squad-chip239 km-portrait239" title="${HEROES[i].name}" style="${kmPortrait239(i)}"><span>Lv.${HEROES[i].level}</span></div>`).join(''):'<span style="font-size:11px;color:#9ab0c8">원정대에 영웅을 편성하세요.</span>';};
const kmSquadOpen239=openSquadModal;openSquadModal=function(){kmSquadOpen239();document.querySelectorAll('#squad-hero-selection-list [onclick^="toggleSquadHero"]').forEach(row=>{const i=Number(row.getAttribute('onclick').match(/\d+/)?.[0]);const icon=row.querySelector('i');if(icon){const holder=icon.parentElement;holder.className='km-portrait239';holder.setAttribute('style',kmPortrait239(i));holder.replaceChildren();}});};
document.addEventListener('DOMContentLoaded',()=>{['gold','food','herb','magic'].forEach(key=>{const el=document.getElementById('cost-'+key);if(el){el.parentElement.querySelector('i')?.remove();el.insertAdjacentHTML('beforebegin',kmResourceArt238(key==='magic'?'magicDust':key));}});});
document.addEventListener('keydown',e=>{const modal=document.getElementById('km-hero-detail239');if(modal.hidden||e.key!=='Tab')return;const list=[...modal.querySelectorAll('button:not(:disabled)')],first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
const kmRefreshBuild239=kmRefreshBuild238;kmRefreshBuild238=function(){kmRefreshBuild239();if(!v15BuildTarget)return;let line=document.getElementById('km-action-cost239');if(!line){line=document.createElement('div');line.id='km-action-cost239';document.querySelector('.km-detail-actions239')?.prepend(line);}const {kind,key}=v15BuildTarget,obj=kind==='building'?BUILDINGS[key]:GATHERING_NODES[key],cfg=kind==='building'?'building':'gathering',job=gameState.upgradesInProgress[(kind==='building'?'building:':'gather:')+key];const value=job?'완료까지 '+Math.max(0,Math.ceil((job.endTime-Date.now())/1000))+'초':(KM_RESOURCE_VIEW_238[obj.costType]?.[0]||obj.costType)+' '+formatNumber(kmGrowthCostV217(obj.baseCost,obj.level,cfg))+' · '+kmGrowthTimeV217(obj.level,cfg)+'초';if(line.textContent!==value)line.textContent=value;};
